### ISSUE TITLE
Blocking error in "Manage Workflow Groups" with the extension enabled

### ISSUE THREAD

**Issue by bollewolle** [piejanssens/sf-toolbox#1] opened 2024-09-10 09:47 UTC
With the Extension activated (in either Edge or Chrome), when I go to "Manage Workflow Groups" in SuccessFactors, I do not get the normal screen but a popup with error that looks like this:
 
![image](https://github.com/user-attachments/assets/591f8b39-edc7-4910-802d-d279128163cc)

Content of the error message is:
`errorId=null, timestamp=null, errorMessage=Assignment to constant variable., errorName=TypeError, server=167pc57bcf29, versionInfo=Release%3A%20%20%2020240823174129%0AServer%3A%20%20%20%20167pc57bcf29%0ATimestamp%3A%202024-09-10T09%3A46%3A20.697%2B0000`

I have this for all customers, even after cleaning cache and such, and I have it for both Preview and Production instances.

However, when I disable the Extension all works fine again. 

Do let me know if you need more information.

**Comment by piejanssens** [comment] 2024-09-18 08:32
![image](https://github.com/user-attachments/assets/13a312fe-d5bc-42d2-9736-d150c8801afd)
Source: https://hcm-eu10.hr.cloud.sap/ui/dynamicgroups/js/dynamicgroup/dynamicgrouplist_b5359b66a733dca215d55b91b9755a8d.js

Bug: no proper initialization of the variable 'i' at *search* `for(i=0` (should be `for(let i=0`).

I have no idea why it's throwing the exception with the sf-toolbox extension enabled though...
I'll try to raise a case to get it fixed in SF.

**Comment by piejanssens** [comment] 2024-09-18 08:50
Root cause identified: global variable collision inside injection script
Fixed: https://github.com/piejanssens/sf-toolbox/commit/8aa0b42907bb608e27105b9e1b35e81dde3eaf62
Part of 1.2.2 release.

**Closed as completed by piejanssens** 2024-09-18 08:50 UTC
Labels: bug
